on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Set Up Go
          uses: actions/setup-go@v5
          with:
            go-version: 1.24.1

        - name: Lint
          uses: golangci/golangci-lint-action@v7
          with:
            version: latest

        - name: Vet
          run: go vet ./...

        - name: Build
          run: go build -v ./...

        - name: Test
          run: go test -v ./...


          

        

