on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Set Up Go
          uses: actions/setup-go@v5
          with:
            go-version: 1.24.1

        - name: Lint
          uses: golangci/golangci-lint-action@v7
          with:
            version: latest

        - name: Vet
          run: go vet ./...

        - name: Build
          run: go build -v -o http-server ./cmd/main.go

        - name: Test
          run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

        - name: Check coverage
          run: |
            coverage=$(go tool cover -func=coverage.txt | grep total | awk '{print $3}' | sed 's/%//')
            echo "Code coverage: $coverage%"
            if (( $(echo "$coverage < 80" | bc -l) )); then
              echo "Coverage is less than 80%"
              exit 1
            fi


          

        

